#+title: Stock Margin
#+STARTUP: hideblocks
#+PROPERTY: header-args :results output :exports both
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup


When an investor buys or shorts a stock on margin, they are using money from their broker.  Simply stated:

- Buying stock on margin means the investor receives a loan from their broker, with the stock as collateral.
- Shorting stock on margin means the investor receives a loan from their broker, with the cash proceeds from the short as collateral.

What should be clear to you by the end of the presentation, is that the margin loan is very safe.  Further, since the average investor doesn't know this, brokers are able to charge interest rates which are too high for their level of risk.  Thus, margin lending is a lucrative profit source for brokerages.

Lastly, note market behaves differently in futures and other derivatives markets, and so what follows should only be applied to stock purchases. 


* Calculating Margin Percent

** Buying (Long) Stock

#+BEGIN_SRC python :eval no
def long_margin_percent(purchase_price, number_shares, initial_margin_percent, present_price):
    loan_amount = purchase_price * number_shares * (1 - initial_margin_percent)
    margin_percent = (present_price * number_shares - loan_amount) / (present_price * number_shares)
    return margin_percent

print("New margin percent is: ", round(100 * long_margin_percent(purchase_price = 100, number_shares = 100, initial_margin_percent = 0.6, present_price = 70), 2), "%")
#+END_SRC


#+BEGIN_SRC C
double long_margin_percent(double purchase_price, double number_shares, double initial_margin_percent, double present_price)
{
    double loan_amount = purchase_price * number_shares * (1 - initial_margin_percent);
    double margin_percent = (present_price * number_shares - loan_amount) / (present_price * number_shares);
    return margin_percent;
}

printf("New margin percent is: %f\%\n", long_margin_percent(100, 100, 0.6, 70));
#+END_SRC

#+RESULTS:
: New margin percent is: 0.428571%


** Shorting (Short) Stock

#+BEGIN_SRC C
double short_margin_percent(double sale_price, double number_shares, double initial_margin_percent, double present_price)
{
    double K = sale_price * number_shares + sale_price * number_shares * initial_margin_percent;
    double margin_percent = (K - present_price * number_shares) / (present_price * number_shares);
    return margin_percent;
}

printf("New margin percent is: %f\%\n", short_margin_percent(100, 100, 0.6, 95));
#+END_SRC

#+RESULTS:
: New margin percent is: 0.684211%



* Margin Call

** Maintenance Margin

To protect their loan, your broker sets a maintenance margin percent.  If your percent margin decreases to the maintenance margin, this triggers a =margin call=.  A =margin call= meas you haveto put in more cash to increase your margin, or your broker will close your position.

** Calculation

To calculate the price at which we get a margin call, we simply set our margin percent calculations above equal to the maintenance margin, and solve for the new price.

*** Price Triggering Margin Call (Long) 

*** Price Triggering Margin Call (Short) 
